### ISSUE TITLE
"ERROR: Cannot find the fakeroot directory"

### ISSUE THREAD

**Issue by karasuhebi** [kelderek/connectwisecontrol-arch#1]
I'm trying to run this on my Steam Deck (currently running SteamOS) but I get the above error when I try running the **makepkg -si** command. Any ideas of what I can try?

**Comment by karasuhebi** [comment]
I tried installing fakeroot by using **sudo pacman -S fakeroot** (which first required I run **sudo pacman-key --populate archlinux**) but it failed with some warnings about not being able to create some directories. I assumed this was because SteamOS is an immutable OS so I ran **sudo steamos-readonly disable** to turn off read-only and then I was able to install fakeroot. I then tried running the **makepkg -si** command again and it worked.

**Comment by kelderek** [comment]
Sounds like you found the issue.  I haven't tried installing connectwise on my Steam Deck, but it makes sense that the immutable OS would prevent a normal install.  IIRC the only official ways to install new apps are through steam or flatpak
